name       : python-appdirs
version    : 1.4.4
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/a/appdirs/appdirs-1.4.4.tar.gz : 7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    small Python module for determining appropriate platform-specific dirs
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
