name       : python-appdirs
version    : 1.4.3
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/a/appdirs/appdirs-1.4.3.tar.gz : 9e5896d1372858f8dd3344faf4e5014d21849c756c8d5701f78f8a103b372d92
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    small Python module for determining appropriate platform-specific dirs
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check     : |
    %python_test
    %python3_test
