name       : python-appdirs
version    : 1.4.0
release    : 1
source     :
    - https://pypi.python.org/packages/bd/66/0a7f48a0f3fb1d3a4072bceb5bbd78b1a6de4d801fb7135578e7c7b1f563/appdirs-1.4.0.tar.gz : 8fc245efb4387a4e3e0ac8ebcc704582df7d72ff6a42a53f5600bbb18fdaadc5
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    small Python module for determining appropriate platform-specific dirs
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
