name       : python-appdirs
version    : 1.4.3
release    : 2
source     :
    - https://pypi.python.org/packages/48/69/d87c60746b393309ca30761f8e2b49473d43450b150cb08f3c6df5c11be5/appdirs-1.4.3.tar.gz : 9e5896d1372858f8dd3344faf4e5014d21849c756c8d5701f78f8a103b372d92
license    : MIT
component  : programming.python
summary    : A small Python module for determining appropriate platform-specific dirs
description: |
    small Python module for determining appropriate platform-specific dirs
build      : |
    %python_setup
install    : |
    %python_install
